"""empty message

Revision ID: d9e888d06967
Revises: dfa8199b17b1
Create Date: 2022-04-29 20:15:32.961375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e888d06967'
down_revision = 'dfa8199b17b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_table',
    sa.Column('NODE_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NODE_NAME', sa.String(length=15), nullable=False),
    sa.Column('NODE_IP', sa.String(length=128), nullable=False),
    sa.Column('NODE_TYPE', sa.String(length=15), nullable=False),
    sa.Column('NODE_NOTE', sa.String(length=15), nullable=True),
    sa.Column('NODE_STATE', sa.String(length=128), nullable=False),
    sa.Column('NODE_TIME', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('NODE_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_table')
    # ### end Alembic commands ###
